spring:
  servlet:
    multipart:
      max-file-size: 8MB      # ← сколько разрешаем одному файлу
      max-request-size: 8MB   # ← сколько всему запросу
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: Muhammad2323.

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
